require('nvim-treesitter.configs').setup {
  highlight = {
    enable = true,
  },
  incremental_selection = {
    enable = true,
    keymaps = {
      init_selection = 'gnn',
      node_incremental = 'grn',
      scope_incremental = 'grc',
      node_decremental = 'grm',
    },
  },
  indent = {
    enable = true,
  },
  textobjects = {
    select = {
      enable = true,
      lookahead = true,
      keymaps = {
        ['ak'] = '@block.outer',
        ['ik'] = '@block.inner',
        ['ac'] = '@call.outer',
        ['ic'] = '@call.inner',
        ['as'] = '@class.outer',
        ['is'] = '@class.inner',
        ['ax'] = '@comment.outer',
        ['am'] = '@function.outer',
        ['im'] = '@function.inner',
        ['ao'] = '@loop.outer',
        ['io'] = '@loop.inner',
        ['ag'] = '@parameter.outer',
        ['ig'] = '@parameter.inner',
      },
    },
    move = {
      enable = true,
      set_jumps = true,
      goto_next_start = {
        [']k'] = '@block.outer',
        [']c'] = '@call.outer',
        [']s'] = '@class.outer',
        [']x'] = '@comment.outer',
        [']m'] = '@function.outer',
        [']o'] = '@loop.outer',
        [']g'] = '@parameter.outer',
      },
      goto_next_end = {
        [']K'] = '@block.outer',
        [']C'] = '@call.outer',
        [']S'] = '@class.outer',
        [']X'] = '@comment.outer',
        [']M'] = '@function.outer',
        [']O'] = '@loop.outer',
        [']G'] = '@parameter.outer',
      },
      goto_previous_start = {
        ['[k'] = '@block.outer',
        ['[c'] = '@call.outer',
        ['[s'] = '@class.outer',
        ['[x'] = '@comment.outer',
        ['[m'] = '@function.outer',
        ['[o'] = '@loop.outer',
        ['[g'] = '@parameter.outer',
      },
      goto_previous_end = {
        ['[K'] = '@block.outer',
        ['[C'] = '@call.outer',
        ['[S'] = '@class.outer',
        ['[X'] = '@comment.outer',
        ['[M'] = '@function.outer',
        ['[O'] = '@loop.outer',
        ['[G'] = '@parameter.outer',
      },
    },
  },
}
